

branches:
  only:
    - master

skip_tags: true

skip_branch_with_pr: true



version: 1.30-appveyor{build}



image: Visual Studio 2019

clone_depth: 2500

cache:
  - build\externals

install:
  - build\download_externals.cmd auto



before_build:
  - build\auto\appveyor_set_version.cmd

build_script:
  - build\auto\build_openmpt_args.cmd vs2019 win10 Win32 Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 win10 x64   Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 win10 ARM   Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 win10 ARM64 Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 win7  Win32 Release 7z default
  - build\auto\build_openmpt_args.cmd vs2019 win7  x64   Release 7z default

after_build:
  - build\auto\build_openmpt_release_packages_multiarch.cmd auto
  - build\auto\package_openmpt_installer_multiarch_args.cmd vs2019 win10 Win32 Release 7z default
  - appveyor PushArtifact bin\openmpt-pkg.win-multi.tar



test: off

