
language: c++

sudo: required

env:
  global:
    - MAKEFLAGS="-j 2"
    - CCACHE_CPP2=1

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: focal
      arch: s390x
    - os: linux
      dist: focal
      arch: ppc64le
    - os: linux
      dist: focal
      arch: arm64
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12u

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zip unzip p7zip xz-utils make binutils gcc g++ clang pkg-config help2man doxygen autoconf autoconf-archive automake libtool ccache zlib1g-dev libmpg123-dev libogg-dev libvorbis-dev portaudio19-dev libpulse-dev libflac-dev libsndfile1-dev libltdl-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ "$(uname -m)" == "x86_64" ]]; then sudo apt-get install -y tcc ; fi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile ; fi

install:
  - true

script:
  - make STRICT=1 NO_SDL=1 NO_SDL2=1
  - make STRICT=1 NO_SDL=1 NO_SDL2=1 check

